In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame(data=pd.read_csv('cars.ORG.csv'))
df.head(-3)

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification,Identification.ID,Identification.Make,Identification.Model Year,Identification.Year,Engine Information.Engine Statistics.Horsepower,Engine Information.Engine Statistics.Torque
0,140,143,202,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission,2009 Audi A3 3.2,Audi,2009 Audi A3,2009,250,236
1,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T AT,Audi,2009 Audi A3,2009,200,207
2,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission,2009 Audi A3 2.0 T,Audi,2009 Audi A3,2009,200,207
3,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
4,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5068,3,253,201,Four-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,17,Gasoline,24,Automatic transmission,2012 Honda Pilot LX 4WD,Honda,2012 Honda Pilot,2012,250,253
5069,3,253,201,Front-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,18,Gasoline,25,Automatic transmission,2012 Honda Pilot EX,Honda,2012 Honda Pilot,2012,250,253
5070,3,253,201,Four-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,17,Gasoline,24,Automatic transmission,2012 Honda Pilot EX 4WD,Honda,2012 Honda Pilot,2012,250,253
5071,13,253,201,Front-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,18,Gasoline,25,Automatic transmission,2012 Honda Pilot EX-L,Honda,2012 Honda Pilot,2012,250,253
5072,141,249,108,All-wheel drive,Lamborghini 5.2L 10 cylinder 552 hp 398 ft-lbs,True,6,6 Speed Manual,12,Gasoline,20,Manual transmission,2012 Lamborghini Gallardo Coupe LP 560-4,Lamborghini,2012 Lamborghini Gallardo Coup,2012,552,398

In [3]:
df_new=df[['Dimensions.Height','Dimensions.Length','Dimensions.Width','Engine Information.Number of Forward Gears',
          'Fuel Information.City mpg','Engine Information.Engine Statistics.Horsepower','Identification.Make']]

In [4]:
df_new

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Number of Forward Gears,Fuel Information.City mpg,Engine Information.Engine Statistics.Horsepower,Identification.Make
0,140,143,202,6,18,250,Audi
1,140,143,202,6,22,200,Audi
2,140,143,202,6,21,200,Audi
3,140,143,202,6,21,200,Audi
4,140,143,202,6,21,200,Audi
...,...,...,...,...,...,...,...
5071,13,253,201,5,18,250,Honda
5072,141,249,108,6,12,552,Lamborghini
5073,160,249,108,6,12,552,Lamborghini
5074,200,210,110,6,17,315,BMW
5075,200,94,110,6,17,315,BMW

In [5]:
x=df_new.drop('Identification.Make',axis=1)
x

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Number of Forward Gears,Fuel Information.City mpg,Engine Information.Engine Statistics.Horsepower
0,140,143,202,6,18,250
1,140,143,202,6,22,200
2,140,143,202,6,21,200
3,140,143,202,6,21,200
4,140,143,202,6,21,200
...,...,...,...,...,...,...
5071,13,253,201,5,18,250
5072,141,249,108,6,12,552
5073,160,249,108,6,12,552
5074,200,210,110,6,17,315
5075,200,94,110,6,17,315

In [6]:
y=df_new['Identification.Make']
y

0              Audi
1              Audi
2              Audi
3              Audi
4              Audi
           ...
5071          Honda
5072    Lamborghini
5073    Lamborghini
5074            BMW
5075            BMW
Name: Identification.Make, Length: 5076, dtype: object

In [7]:
df_new.columns

Index(['Dimensions.Height', 'Dimensions.Length', 'Dimensions.Width',
       'Engine Information.Number of Forward Gears',
       'Fuel Information.City mpg',
       'Engine Information.Engine Statistics.Horsepower',
       'Identification.Make'],
      dtype='object')

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
model=RandomForestClassifier(n_estimators=100)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

In [12]:
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [13]:
print(model.feature_importances_)

[0.1972965  0.20141281 0.22984315 0.06450565 0.10913561 0.19780628]

In [14]:
feature_importances=pd.Series(model.feature_importances_,index=df_new.columns)\
                      .sort_values(ascending=False)

ValueError: Length of values (6) does not match length of index (7)